### ISSUE TITLE
"skip-shebang": false doesn't have default

### ISSUE THREAD

**Issue by kelunik** [MacFJA/PharBuilder#38] opened 2018-01-08 16:57 UTC
`vendor/bin/phar-builder package composer.json` interactively asks for a value even if it should run and use the default value if no `"skip-shebang": false` is present.

**Comment by MacFJA** [comment] 2018-01-14 22:20
I think I found why this behavoir occurs. I will fix it this week

**Comment by MacFJA** [comment] 2018-01-23 22:30
With a little delay, the PR #39 will solve your issue.  
I will merge it next week if nobody have issue with it

**Comment by MacFJA** [comment] 2018-01-29 20:20
@kelunik Did this PR solve your issue?

**Comment by MacFJA** [comment] 2018-01-30 20:59
I merged the PR #39 

If the issue is still present, please reopen this issue

**Closed as completed by MacFJA** 2018-01-30 20:59 UTC

**Comment by kelunik** [comment] 2018-01-31 06:45
Will do, haven't had time to test this yet.
